// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WindowsFormsApplication2.Models;

[Table("Attendance")]
public partial class Attendance
{
    [Key]
    public int Id { get; set; }

    public int SubscribeId { get; set; }

    [Column(TypeName = "date")]
    public DateTime AttendanceDate { get; set; }

    [ForeignKey("SubscribeId")]
    [InverseProperty("Attendances")]
    public virtual Subscription Subscribe { get; set; }
}