// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WindowsFormsApplication2.Models;

public partial class Money
{
    [Key]
    public int Id { get; set; }

    public int SubscribeId { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal TotalAmount { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal PaidAmount { get; set; }

    [Column(TypeName = "date")]
    public DateTime PaymentDate { get; set; }

    [ForeignKey("SubscribeId")]
    [InverseProperty("Money")]
    public virtual Subscription Subscribe { get; set; }
}