// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WindowsFormsApplication2.Models;

[Table("Subscription")]
public partial class Subscription
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    [StringLength(50)]
    public string SubscriptionPeriod { get; set; }

    [StringLength(50)]
    public string Type { get; set; }

    public bool PaymentHasBeenMade { get; set; }

    [InverseProperty("Subscribe")]
    public virtual ICollection<Attendance> Attendances { get; set; } = new List<Attendance>();

    [InverseProperty("Subscribe")]
    public virtual ICollection<Money> Money { get; set; } = new List<Money>();
}